INSERT INTO fabricante (ID,NOME,DESCRICAO) VALUES (1,'Ford','Fabricante de automóveis');
INSERT INTO fabricante (ID,NOME,DESCRICAO) VALUES (2,'Mercedes-Benz','Marca de automóveis');
INSERT INTO fabricante (ID,NOME,DESCRICAO) VALUES (3,'Porsche','Marca de automóveis');
INSERT INTO fabricante (ID,NOME,DESCRICAO) VALUES (4,'Ferrari','Fabricante de automóveis');
INSERT INTO fabricante (ID,NOME,DESCRICAO) VALUES (5,'Hummer','Fabricante de automóveis');
INSERT INTO fabricante (ID,NOME,DESCRICAO) VALUES (6,'Pontiac','Fabricante de automóveis');
INSERT INTO fabricante (ID,NOME,DESCRICAO) VALUES (7,'Audi','Fabricante de automóveis');

INSERT INTO motorista (ID,NOME,SEXO,CPF,CNH)
VALUES(1,'Cláudio Benjamin Fernandes','MASCULINO','517.945.818-80','92710488655');
INSERT INTO motorista (ID,NOME,SEXO,CPF,CNH)
VALUES(2,'Silvana Sueli Valentina Gomes','FEMININO','634.615.119-35','77064355585');
INSERT INTO motorista (ID,NOME,SEXO,CPF,CNH)
VALUES(3,'Marcos Renato Carlos Ferreira','MASCULINO','611.688.127-04','82354211954');
INSERT INTO motorista (ID,NOME,SEXO,CPF,CNH)
VALUES(4,'Sebastiana Joana Silva','FEMININO','815.909.058-73','09336461345');


INSERT INTO MODELO (ID , DESCRICAO , CATEGORIA , FABRICANTE_ID) VALUES (1,'Ford Focus','HATCH', 1);	
INSERT INTO MODELO (ID , DESCRICAO , CATEGORIA , FABRICANTE_ID) VALUES (2,'Ford KA','HATCH', 1);
INSERT INTO MODELO (ID , DESCRICAO , CATEGORIA , FABRICANTE_ID) VALUES (3,'Ferrari FS1','ESPORTIVO', 4);
INSERT INTO MODELO (ID , DESCRICAO , CATEGORIA , FABRICANTE_ID) VALUES (4,'Ferrari 488','ESPORTIVO', 4);
INSERT INTO MODELO (ID , DESCRICAO , CATEGORIA , FABRICANTE_ID) VALUES (5,'Ferrari Portofino','ESPORTIVO', 4);
INSERT INTO MODELO (ID , DESCRICAO , CATEGORIA , FABRICANTE_ID) VALUES (6,'Porche 911','ESPORTIVO', 3);